version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user/ad-request-form
permissions:
- object: /home/ec2-user/ad-request-form
  pattern: "**"
  owner: ec2-user
  type:
    - file
hooks:
ApplicationStop:
   - location: aws_deploy_scripts/app-stop.sh
     timeout: 10
     runas: ec2-user
BeforeInstall:
   - location: aws_deploy_scripts/before-install.sh
     timeout: 1200
     runas: root
Install:
   - location: aws_deploy_scripts/install.sh
     timeout: 1200
     runas: root
AfterInstall:
   - location: aws_deploy_scripts/install-pkgs.sh
     timeout: 1200
     runas: ec2-user
ApplicationStart:
   - location: aws_deploy_scripts/app-start.sh
     timeout: 60
     runas: ec2-user