version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user/ad-request-form
permissions:
- object: /
  pattern: "**"
  owner: ec2-user
hooks:
  ApplicationStop:
     - location: aws_deploy_scripts/app-stop.sh
       timeout: 10
       runas: ec2-user
  AfterInstall:
     - location: aws_deploy_scripts/install-pkgs.sh
       timeout: 3600
       runas: ec2-user
  ApplicationStart:
     - location: aws_deploy_scripts/app-start.sh
       timeout: 60
       runas: ec2-user